# Generated by Django 6.0.6 on 2026-06-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=150)),
                ('endpoint', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='api_auditlo_user_5cb864_idx'), models.Index(fields=['action', '-timestamp'], name='api_auditlo_action_e9644f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('wealth_idx', models.FloatField()),
                ('education', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('has_diabetes', models.BooleanField()),
                ('has_htn', models.BooleanField()),
                ('DVS', models.FloatField()),
                ('TNS', models.FloatField()),
                ('ICS', models.FloatField()),
                ('CCS', models.FloatField()),
                ('HCFD_score', models.FloatField()),
                ('rule_score', models.FloatField()),
                ('anomaly_score', models.FloatField()),
                ('final_risk', models.FloatField(help_text='Risk score between 0 and 1')),
                ('risk_tier', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], db_index=True, max_length=20)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['caseid'], name='api_transac_caseid_9aa3ff_idx'), models.Index(fields=['risk_tier', '-created_at'], name='api_transac_risk_ti_ac8ea6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tier', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], db_index=True, max_length=20)),
                ('final_risk', models.FloatField(help_text='Risk score at time of alert')),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.transaction')),
            ],
            options={
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='api_alert_is_reso_b9f745_idx'), models.Index(fields=['risk_tier', '-created_at'], name='api_alert_risk_ti_5e7351_idx')],
            },
        ),
    ]
