# Generated by Django 6.0.6 on 2026-06-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainabilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores from model')),
                ('shap_values', models.JSONField(blank=True, default=dict, help_text='SHAP values for each feature')),
                ('rule_violations', models.JSONField(default=list, help_text='List of medical rule violations')),
                ('key_factors', models.JSONField(default=list, help_text='Top factors contributing to risk score')),
                ('model_versions', models.JSONField(default=dict, help_text='Versions of models used (XGBoost, Isolation Forest, etc.)')),
                ('explanation_text', models.TextField(help_text='Human-readable explanation of the prediction')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Model confidence in prediction (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explainability', to='api.transaction')),
            ],
            options={
                'verbose_name_plural': 'Explainability Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('xgboost', 'XGBoost'), ('isolation_forest', 'Isolation Forest'), ('autoencoder', 'Autoencoder'), ('hcfd', 'HCFD Ensemble'), ('rule_engine', 'Rule Engine')], db_index=True, max_length=50)),
                ('model_version', models.CharField(help_text='e.g., 1.0.0', max_length=20)),
                ('model_path', models.CharField(help_text='Path to model file (.pkl, .h5, etc.)', max_length=500)),
                ('training_dataset', models.CharField(help_text='e.g., NFHS-5, Custom', max_length=100)),
                ('training_size', models.IntegerField(help_text='Number of training samples')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('auc_roc', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Currently in use for predictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Model Metadata',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='api_modelme_model_t_47f0b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending Review'), ('conditional', 'Conditional Approval')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(help_text='Reason for insurance decision')),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approved coverage amount in currency', max_digits=12, null=True)),
                ('denial_reason', models.CharField(blank=True, help_text='If denied, specify reason', max_length=255)),
                ('reviewer', models.CharField(blank=True, help_text='User who made the decision', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_decision', to='api.transaction')),
            ],
            options={
                'verbose_name_plural': 'Insurance Decisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision', '-created_at'], name='api_insuran_decisio_c21d37_idx')],
            },
        ),
    ]
